language: php
services:
  - docker
before_install:
- cat docker/test/mariadb/.secret.env.dist > docker/test/mariadb/.secret.env
- cat app/config/parameters.yml.dist > app/config/parameters.yml
- |
    if [[ -n "$encrypted_919edf534848_key" ]] && [[ -n "$encrypted_919edf534848_iv" ]]; then
        export BLACKFIRE="on"
        openssl aes-256-cbc -K $encrypted_919edf534848_key -iv $encrypted_919edf534848_iv -in docker/test/blackfire/.secret.env.enc.key.enc -out docker/test/blackfire/.secret.env.enc.key -d
        openssl aes-256-cbc -kfile docker/test/blackfire/.secret.env.enc.key -in docker/test/blackfire/.secret.env.enc -out docker/test/blackfire/.secret.env -d
    else
        export BLACKFIRE="off"
    fi
install:
- cd docker/test && docker-compose up -d
- docker exec -t todolisttest_php_1 /bin/sh -c "apk add --no-cache composer"
- docker exec -t todolisttest_php_1 /bin/sh -c "cd /app && composer install"
- docker exec -t todolisttest_php_1 /bin/sh -c "/app/bin/console doctrine:schema:create"
- docker exec -t todolisttest_php_1 /bin/sh -c "/app/bin/console doctrine:fixtures:load --no-interaction"
script:
- docker exec -t todolisttest_php_1 /bin/sh -c "cd /app && phpdbg -qrr vendor/bin/phpunit --coverage-text --strict-coverage --strict-global-state"
- docker exec -t todolisttest_php_1 /bin/sh -c "/app/vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no --config /app/.php_cs.dist"
- docker exec -t todolisttest_php_1 /bin/sh -c "/app/bin/console lint:yaml /app/app/config"
- docker exec -t todolisttest_php_1 /bin/sh -c "/app/bin/console lint:twig /app/app/Resources/views"
- docker exec -t todolisttest_php_1 /bin/sh -c "/app/bin/console doctrine:schema:validate --no-interaction --skip-sync"