services:
  - docker
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_b93f56ee5fe5_key -iv $encrypted_b93f56ee5fe5_iv -in docker/test/mariadb/.secret.env.enc.key.enc -out docker/test/mariadb/.secret.env.enc.key -d
- openssl aes-256-cbc -K $encrypted_919edf534848_key -iv $encrypted_919edf534848_iv -in docker/test/blackfire/.secret.env.enc.key.enc -out docker/test/blackfire/.secret.env.enc.key -d
- docker run -ti -v "docker/test:/wd" frapsoft/openssl enc -d -aes-256-cbc -kfile /wd/mariadb/.secret.env.enc.key -in wd/mariadb/.secret.env.enc -out wd/mariadb/.secret.env
- docker run -ti -v "docker/test:/wd" frapsoft/openssl enc -d -aes-256-cbc -kfile /wd/blackfire/.secret.env.enc.key -in wd/blackfire/.secret.env.enc -out wd/blackfire/.secret.env
install:
- travis_retry composer install
- echo "127.0.0.1 mariadb" >> /etc/hostname
- cd docker/test && docker-compose up -d
before_script:
- phpenv config-rm xdebug.ini || true
- docker exec -ti todo_list_test_php_1 /bin/sh
- cd /app
script:
- vendor/bin/phpunit
- bin/console lint:yaml app/config
- bin/console lint:twig app/Resources/views
- bin/console security:check
- bin/console doctrine:schema:validate --skip-sync --no-interaction