language: php

matrix:
    include:
        - php: 5.5
          env: BLACKFIRE=on
        - php: 7.2
          env: BLACKFIRE=on

sudo: false

cache:
    - $HOME/.composer/cache/files

before_install:
    - |
        if [[ "$BLACKFIRE" = "on" ]]; then
            openssl aes-256-cbc -K $encrypted_df9dcb7decd5_key -iv $encrypted_df9dcb7decd5_iv -in .blackfire.travis.ini.enc -out .blackfire.ini -d
            curl -L https://blackfire.io/api/v1/releases/agent/linux/amd64 | tar zxpf -
            chmod 755 agent && ./agent --config=.blackfire.ini --socket=unix:///tmp/blackfire.sock &
        fi

install:
    - travis_retry composer install

before_script:
    - phpenv config-rm xdebug.ini || true
    - |
        if [[ "$BLACKFIRE" = "on" ]]; then
            curl -L https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$(php -r "echo PHP_MAJOR_VERSION . PHP_MINOR_VERSION;")-zts | tar zxpf -
            echo "extension=$(pwd)/$(ls blackfire-*.so | tr -d '[[:space:]]')" > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/blackfire.ini
            echo "blackfire.agent_socket=unix:///tmp/blackfire.sock" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/blackfire.ini
        fi

script:
    - vendor/bin/phpunit
    #- vendor/bin/php-cs-fixer fix --diff --dry-run -v
    - bin/console lint:yaml app/config
    - bin/console lint:twig app/Resources/views
    - bin/console security:check
    - bin/console doctrine:schema:validate --skip-sync --no-interaction
